# for some reference: https://stefanscherer.github.io/use-appveyor-to-build-multi-arch-docker-image/
version: '1.0.{build}'

image:
  - Visual Studio 2017
  - Ubuntu

environment:
  GEO_VERSION: '18b'

for:
# Windows w/64 bit Geo & python 3.6
-
  matrix:
    only:
      - image: Visual Studio 2017

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.6"
      PYTHON_ARCH: "64"

  environment:
    GEO_BIT: '64'
  #cmd: set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%


# Windows w/64 bit Geo & python 2.7
-
  matrix:
    only:
      - image: Visual Studio 2017
    - PYTHON: "C:\\Python27.10-x64"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "64"

  environment:
    GEO_BIT: '32'
  #cmd: set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%


# Windows w/32 bit Geo & python 3.6
-
  matrix:
    only:
      - image: Visual Studio 2017
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.6"
      PYTHON_ARCH: "32"

  environment:
    GEO_BIT: '32'
  #cmd: set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%


# Windows w/32 bit Geo & python 2.7
-
  matrix:
    only:
      - image: Visual Studio 2017
    - PYTHON: "C:\\Python27.10"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "32"

  environment:
    GEO_BIT: '32'
  #cmd: set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%


# Ubuntu - python 2.7
-
  matrix:
    only:
      - image: Ubuntu

# Ubuntu - python 3.6
-
  matrix:
    only:
      - image: Ubuntu
  sh: alias python=python3
  sh: alias pip=pip3


install:
  - ps ./appveyor/install.ps1
  # - sh ./appveyor/install-linux.sh

test_script:
  - pip install -e .[dev]
  - invoke test all
